apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs-rhtap-sample1
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdave-tenant/nodejs-rhtap-example/nodejs-rhtap-sample1@sha256:91bf57d47f726836cba5c3aec6990c7a28fdf88504098b21dcb0130d035e621b
        name: my-nodejs
        resources: {}
status: {}
