apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-rhtap-sample1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-rhtap-sample1
    app.kubernetes.io/part-of: nodejs-rhtap-example
  name: nodejs-rhtap-sample1bewn
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: nodejs-rhtap-sample1
    weight: null
status: {}
